services:
  postgres:
    container_name: nestjs_postgres_local
    image: postgres:16.6
    shm_size: 1g
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./.docker/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - nestjs_postgres_local:/var/lib/postgresql/data
    networks:
      - ltp
  pgadmin:
    container_name: nestjs_pgadmin_local
    image: dpage/pgadmin4:8.14.0
    shm_size: 1g
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - nestjs_pgadmin_local:/var/lib/pgadmin
    networks:
      - ltp
networks:
  ltp:
volumes:
  nestjs_postgres_local:
  nestjs_pgadmin_local:
